Update for 4.9.2 tag and add a tagging script
svn path=/trunk/kde-common/release/; revision=1318888

diff --git a/dist b/dist
--- a/dist
+++ b/dist
@@ -6,7 +6,7 @@
   if test $isl10n -eq 1; then
     cd $package
     cat subdirs | while read lang; do
-      scripts/autogen.sh $lang || exit 1
+      scripts/autogen.sh $lang || echo "ERROR with: $lang"
     done
   fi
 
